Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -25,7 +25,7 @@ jobs:
 
     - name: Read Building Configuration
       run: |
-        CONFIG_ENV=config.env.simple
+        CONFIG_ENV=config_violet_4.14.env
         echo "KERNEL_SOURCE=$(cat $CONFIG_ENV | grep -w "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
         echo "KERNEL_SOURCE_BRANCH=$(cat $CONFIG_ENV | grep -w "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
         echo "KERNEL_CONFIG=$(cat $CONFIG_ENV | grep -w "KERNEL_CONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
@@ -209,17 +209,37 @@ jobs:
           unzip android-kernel.zip -d android-kernel/
         fi
 
-    - name: Download source boot image
+    - name: Download KenrelSU source boot image
       if: env.BUILD_KERNELSU_BOOT_IMG == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         mkdir bootimg_tmp
         wget -O ./bootimg_tmp/boot-source-kernelsu.img ${{ env.KERNELSU_SOURCE_BOOT_IMAGE }}
         if [ -f ./bootimg_tmp/boot-source-kernelsu.img ]; then
-            echo "HAVE_KERNELSU_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
-            echo "SOURCE_KERNELSU_BOOTIMG_PATH=$GITHUB_WORKSPACE/kernel_workspace/bootimg_tmp/boot-source-kernelsu.img" >> $GITHUB_ENV
+          echo "HAVE_KERNELSU_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
+          echo "SOURCE_KERNELSU_BOOTIMG_PATH=$GITHUB_WORKSPACE/kernel_workspace/bootimg_tmp/boot-source-kernelsu.img" >> $GITHUB_ENV
+        else
+          echo "KernelSU source boot image is empty or broken."
+          exit 1
         fi
-        
+    
+    - name: Download Magisk source boot image
+      if: env.ENABLE_MAGISK == 'true'
+      run: |
+        cd $GITHUB_WORKSPACE/kernel_workspace
+        mkdir magisk-patch
+        cd magisk-patch
+        mkdir magisk
+        cd magisk
+        wget "${{ env.MAGISK_SOURCE_BOOT_IMAGE }}" -O ${{ env.MAGISK_PATCH_PARTITION }}.img
+        if [ -f ./${{ env.MAGISK_PATCH_PARTITION }}.img ]; then
+          echo "HAVE_MAGISK_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
+          echo "SOURCE_MAGISK_BOOTIMG_PATH=$GITHUB_WORKSPACE/kernel_workspace/magisk-patch/magisk/${{ env.MAGISK_PATCH_PARTITION }}.img" >> $GITHUB_ENV
+        else
+          echo "Magisk source boot image is empty or broken."
+          exit 1
+        fi
+    
     - name: Setup KernelSU
       if: env.ENABLE_KERNELSU == 'true'
       run: |
@@ -288,14 +308,14 @@ jobs:
        if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
            echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
        else
-           echo "Kernel output file is empty"
+           echo "Kernel output file is empty or broken."
            exit 1
        fi
        if [ ${{ env.NEED_DTBO }} = true ]; then
            if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/dtbo.img ]; then
                echo "CHECK_DTBO_IS_OK=true" >> $GITHUB_ENV
            else
-               echo "DTBO image is empty"
+               echo "DTBO image is empty or broken."
                exit 1
            fi
        fi
@@ -314,6 +334,12 @@ jobs:
         fi
         cd ./AnyKernel3/
         zip -r AnyKernel3 . -x ".git*" -x "README.md" -x "*.zip"
+        if [ -f android-kernel/out/arch/${{ env.ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
+           echo "AK3_IS_OK=true" >> $GITHUB_ENV
+        else
+           echo "AnyKernel3 output file is empty or broken."
+           exit 1
+        fi
 
     - name: Make KernelSU boot image
       if: env.HAVE_KERNELSU_SOURCE_BOOT_IMAGE == 'true' && env.CHECK_FILE_IS_OK == 'true'
@@ -342,7 +368,7 @@ jobs:
         if [ -f boot-kernelsu.img ]; then
             echo "MAKE_KERNELSU_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
         else
-            echo "Boot image is empty"
+            echo "Magisk Boot image is empty or broken."
             exit 1
         fi
     
@@ -355,18 +381,28 @@ jobs:
         sudo apt install -y rename
         mkdir magisk
         cd magisk
-        wget "${{ env.MAGISK_SOURCE_BOOT_IMAGE }}" -O ${{ env.MAGISK_PATCH_PARTITION }}.img
         wget "${{ env.MAGISK_APK }}" -O Magisk.zip
-        unzip Magisk.zip >> /dev/null
-        cd ./lib/x86_64
-        rename 's/(lib|\.so)//g' *
-        cd ../../
-        mv ./lib/x86_64/* ./assets
-        chmod -R a+x ./assets/*
-        cd assets
-        bash ./boot_patch.sh ../${{ env.MAGISK_PATCH_PARTITION }}.img
-        mv ./new-boot.img $GITHUB_WORKSPACE/kernel_workspace/magisk-patch/boot-magisk.img
-        echo "MAKE_MAGISK_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
+        if [ -f ./Magisk.zip ]; then
+          echo "HAVE_MAGISK_ZIP=true" >> $GITHUB_ENV
+        else
+          echo "Magisk Installer is empty or broken."
+          exit 1
+        fi
+        if [ ${{ env.HAVE_MAGISK_ZIP }} = true ] && [ ${{ env.HAVE_MAGISK_SOURCE_BOOT_IMAGE }} = true ]; then
+          unzip Magisk.zip >> /dev/null
+          cd ./lib/x86_64
+          rename 's/(lib|\.so)//g' *
+          cd ../../
+          mv ./lib/x86_64/* ./assets
+          chmod -R a+x ./assets/*
+          cd assets
+          bash ./boot_patch.sh ${{ env.SOURCE_MAGISK_BOOTIMG_PATH }}
+          mv ./new-boot.img $GITHUB_WORKSPACE/kernel_workspace/magisk-patch/boot-magisk.img
+          echo "MAKE_MAGISK_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
+        else
+          echo "Downloading Binaries failed!"
+          exit 1
+        fi
 
     - name: Upload ${{ env.KERNEL_IMAGE_NAME }}
       if: env.CHECK_FILE_IS_OK == 'true'
@@ -377,7 +413,7 @@ jobs:
         if-no-files-found: error
 
     - name: Upload AnyKernel3
-      if: env.CHECK_FILE_IS_OK == 'true'
+      if: env.CHECK_FILE_IS_OK == 'true' && env.AK3_IS_OK == 'true'
       uses: actions/upload-artifact@v3
       with:
         name: AnyKernel3-${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
@@ -401,7 +437,7 @@ jobs:
         if-no-files-found: error
     
     - name: Upload Magisk boot image
-      if: env.MAKE_MAGISK_BOOT_IMAGE_IS_OK == 'true'
+      if: env.ENABLE_MAGISK == 'true' && env.MAKE_MAGISK_BOOT_IMAGE_IS_OK == 'true'
       uses: actions/upload-artifact@v3
       with:
         name: boot-Magisk-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
@@ -420,7 +456,7 @@ jobs:
       uses: softprops/action-gh-release@master
       if: github.event.inputs.release == 'true'
       with:
-        tag_name: Build-${{ env.BUILD_TIME }}
+        tag_name: Build-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
         draft: false
         prerelease: false
         files: |
